[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
skip-build-docker = true
seeds = true

[programs.localnet]
soundmint = "XsRj5cL2yV7BQehEsJHSEoy3P2Y4YXpogv4E2CJrzYQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
